name: coastsat
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=pyhd3eb1b0_0
  - anyio=4.7.0=py313hca03da5_0
  - appnope=0.1.3=py313hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py313h80987f9_1
  - astropy=7.0.0=py313h80987f9_0
  - astropy-iers-data=0.2025.1.13.0.34.51=py313hca03da5_0
  - asttokens=3.0.0=py313hca03da5_0
  - async-lru=2.0.4=py313hca03da5_0
  - attrs=24.3.0=py313hca03da5_0
  - babel=2.16.0=py313hca03da5_0
  - beautifulsoup4=4.12.3=py313hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py313hca03da5_0
  - blosc=1.21.3=h313beb8_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.4.2=py313ha35b7ea_0
  - branca=0.6.0=py313hca03da5_0
  - brotli-python=1.0.9=py313h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.2.25=hca03da5_0
  - cairo=1.16.0=hd886ae0_6
  - certifi=2025.6.15=py313hca03da5_0
  - cffi=1.17.1=py313h3eb5a62_1
  - cfitsio=3.470=h7f6438f_7
  - cftime=1.6.4=py313h93df234_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - comm=0.2.1=py313hca03da5_0
  - contourpy=1.3.1=py313h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.8.11=py313h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h313beb8_0
  - folium=0.14.0=py313hca03da5_0
  - fontconfig=2.14.1=h6402c1e_3
  - fonttools=4.55.3=py313h80987f9_0
  - freetype=2.13.3=h47d26ad_0
  - freexl=2.0.0=ha3de405_0
  - gdal=3.6.2=py313h6dafdc7_10
  - geographiclib=2.0=py313hca03da5_0
  - geopandas=1.0.1=py313hca03da5_0
  - geopandas-base=1.0.1=py313hca03da5_0
  - geopy=2.4.1=py313hca03da5_0
  - geos=3.10.6=h313beb8_0
  - geotiff=1.7.0=hcec61be_4
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - h11=0.16.0=py313hca03da5_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.14.5=hd77251f_2
  - httpcore=1.0.9=py313hca03da5_0
  - httpx=0.28.1=py313hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py313hca03da5_0
  - imageio=2.37.0=py313hca03da5_0
  - ipykernel=6.29.5=py313hca03da5_1
  - ipython=9.1.0=py313hca03da5_0
  - ipython_pygments_lexers=1.1.1=py313hca03da5_0
  - jedi=0.19.2=py313hca03da5_0
  - jinja2=3.1.6=py313hca03da5_0
  - joblib=1.4.2=py313hca03da5_0
  - jpeg=9e=h80987f9_3
  - json-c=0.16=h1a28f6b_0
  - json5=0.9.25=py313hca03da5_0
  - jsonschema=4.23.0=py313hca03da5_0
  - jsonschema-specifications=2023.7.1=py313hca03da5_0
  - jupyter-lsp=2.2.5=py313hca03da5_0
  - jupyter_client=8.6.3=py313hca03da5_0
  - jupyter_core=5.7.2=py313hca03da5_0
  - jupyter_events=0.12.0=py313hca03da5_0
  - jupyter_server=2.15.0=py313hca03da5_0
  - jupyter_server_terminals=0.5.3=py313hca03da5_0
  - jupyterlab=4.3.4=py313hca03da5_0
  - jupyterlab_pygments=0.3.0=py313hca03da5_0
  - jupyterlab_server=2.27.3=py313hca03da5_0
  - kealib=1.5.0=h3444380_2
  - kiwisolver=1.4.8=py313h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lazy_loader=0.4=py313hca03da5_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libboost=1.82.0=h0bc93f9_2
  - libcurl=8.12.1=hde089ae_0
  - libcxx=20.1.6=ha82da77_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgdal=3.6.2=hb8790f9_10
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libkml=1.3.0=hc4d7c42_7
  - libmpdec=4.0.0=h80987f9_0
  - libnetcdf=4.8.1=h7d1a7d1_5
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.29=hea593b9_0
  - libpng=1.6.39=h80987f9_0
  - libpq=17.4=h02f6b3c_0
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialite=5.1.0=h4e90699_2
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzip=1.8.0=h62fee54_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mapclassify=2.5.0=py313hca03da5_0
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.0=py313hca03da5_1
  - matplotlib-base=3.10.0=py313hb68df00_0
  - matplotlib-inline=0.1.6=py313hca03da5_0
  - minizip=4.0.3=ha89c15f_0
  - mistune=3.1.2=py313hca03da5_0
  - nbclient=0.10.2=py313hca03da5_0
  - nbconvert-core=7.16.6=py313hca03da5_0
  - nbformat=5.10.4=py313hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py313hca03da5_0
  - netcdf4=1.7.2=py313hc17c79c_1
  - networkx=3.4.2=py313hca03da5_0
  - notebook=7.3.2=py313hca03da5_1
  - notebook-shim=0.2.4=py313hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numexpr=2.10.1=py313h5d9532f_0
  - numpy=2.2.5=py313hdcf7240_0
  - numpy-base=2.2.5=py313h9d8309b_0
  - openjpeg=2.5.2=hba36e21_1
  - openldap=2.6.4=he7ef289_0
  - openssl=3.0.16=h02f6b3c_0
  - overrides=7.4.0=py313hca03da5_0
  - packaging=24.2=py313hca03da5_0
  - pandas=2.2.3=py313hcf29cfe_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py313hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py313h41ba818_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=4.3.7=py313hca03da5_0
  - poppler=24.09.0=hb57d120_2
  - poppler-data=0.4.11=hca03da5_1
  - proj=9.3.1=hdced247_1
  - prometheus_client=0.21.1=py313hca03da5_0
  - prompt-toolkit=3.0.43=py313hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h80987f9_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyerfa=2.0.1.5=py313h80987f9_0
  - pyfes=2024.6.0=py313hf9c7212_4
  - pygments=2.19.1=py313hca03da5_0
  - pyogrio=0.10.0=py313hcf39714_0
  - pyparsing=3.2.0=py313hca03da5_0
  - pyproj=3.6.1=py313hf165acc_1
  - pysocks=1.7.1=py313hca03da5_0
  - python=3.13.5=h2eb94d5_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-fastjsonschema=2.20.0=py313hca03da5_0
  - python-json-logger=3.2.1=py313hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2024.1=py313hca03da5_0
  - pyyaml=6.0.2=py313h80987f9_0
  - pyzmq=26.2.0=py313h313beb8_0
  - qhull=2020.2=h48ca7d4_2
  - rasterio=1.4.3=py313h9ce171c_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py313hca03da5_0
  - requests=2.32.3=py313hca03da5_1
  - rfc3339-validator=0.1.4=py313hca03da5_0
  - rfc3986-validator=0.1.1=py313hca03da5_0
  - rpds-py=0.22.3=py313h2aea54e_0
  - scikit-image=0.25.0=py313h313beb8_0
  - scikit-learn=1.6.1=py313h313beb8_0
  - scipy=1.15.3=py313hd7edaaf_0
  - send2trash=1.8.2=py313hca03da5_1
  - setuptools=72.1.0=py313hca03da5_0
  - shapely=2.0.6=py313hc1b91b6_0
  - six=1.17.0=py313hca03da5_0
  - sniffio=1.3.0=py313hca03da5_0
  - soupsieve=2.5=py313hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py313hca03da5_0
  - threadpoolctl=3.5.0=py313h7eb115d_0
  - tifffile=2025.2.18=py313hca03da5_0
  - tiledb=2.3.3=hb4a6b97_3
  - tinycss2=1.4.0=py313hca03da5_0
  - tk=8.6.14=h6ba3021_1
  - tornado=6.5.1=py313h80987f9_0
  - traitlets=5.14.3=py313hca03da5_0
  - typing-extensions=4.12.2=py313hca03da5_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - uriparser=0.9.7=h80987f9_0
  - urllib3=2.3.0=py313hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py313hca03da5_2
  - websocket-client=1.8.0=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xerces-c=3.2.4=h313beb8_1
  - xyzservices=2022.9.0=py313hca03da5_1
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - adjusttext==1.3.0
      - alembic==1.16.2
      - alphashape==1.3.1
      - cachetools==5.5.2
      - click==8.2.1
      - click-log==0.4.0
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - earthengine-api==1.5.19
      - filelock==3.18.0
      - fsspec==2025.5.1
      - google-api-core==2.25.1
      - google-api-python-client==2.172.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - httplib2==0.22.0
      - imageio-ffmpeg==0.6.0
      - lightgbm==4.6.0
      - llvmlite==0.44.0
      - mako==1.3.10
      - mpmath==1.3.0
      - numba==0.61.2
      - optuna==4.4.0
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - rsa==4.9.1
      - rtree==1.4.0
      - shap==0.48.0
      - slicer==0.0.8
      - sqlalchemy==2.0.41
      - sympy==1.14.0
      - torch==2.7.1
      - tqdm==4.67.1
      - trimesh==4.6.12
      - uritemplate==4.2.0
      - xgboost==3.0.2
prefix: /opt/anaconda3/envs/coastsat
